In [9]:
import numpy as np
import pandas as pd

In [18]:
sim_rem = pd.read_excel("/content/drive/MyDrive/Investigacion/paper AI/results.xlsx", sheet_name="sim_rem")
sim_rem

Unnamed: 0  Mean   Median  Percentile_25  Percentile_75  StandDev
0 2024-08-01    3.9     3.9            3.8            4.0       0.2
1 2024-09-01    3.5     3.5            3.1            3.7       0.6
2 2024-10-01    3.8     3.5            3.1            4.0       1.4
3 2024-11-01    3.5     3.3            2.9            3.9       0.9
4 2024-12-01    3.8     3.6            2.9            4.1       1.5
5 2025-01-01    3.7     3.4            3.0            3.9       1.5
6 2025-02-01    3.4     3.4            2.8            3.9       0.9

In [20]:
sim_rem.Percentile_25.iloc[0]

3.8

In [31]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(0)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[6], scale=sim_rem.StandDev.iloc[6], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[6] - sim_rem.Percentile_25.iloc[6]) + sim_rem.Percentile_25.iloc[6]

# Adjust median
median_adjustment = sim_rem.Median.iloc[6] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
feb_25 = df['Final'].to_numpy()
feb_25

array([4.68606161, 3.53912988, 4.02567216, 5.08704839, 4.77310196,
       2.38081207, 4.00158006, 3.07534834, 3.11582902, 3.54791021,
       3.32375785, 4.42556125, 3.84260285, 3.3049476 , 3.57588331,
       3.48322285, 4.45903469, 3.03010575, 3.46589425, 2.48439886,
       1.05575857, 3.75227156, 3.92955308, 2.57852405, 5.11131864,
       1.97961764, 3.24110762, 3.04522086, 4.49157856, 4.4382468 ,
       3.33292716, 3.52063402, 2.45606813, 1.53692952, 2.91006063,
       3.33410575, 4.23720878, 4.2137379 , 2.8769159 , 2.94841465,
       2.32087517, 2.00850147])

In [30]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(0)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[5], scale=sim_rem.StandDev.iloc[5], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[5] - sim_rem.Percentile_25.iloc[5]) + sim_rem.Percentile_25.iloc[5]

# Adjust median
median_adjustment = sim_rem.Median.iloc[5] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
ene_25 = df['Final'].to_numpy()
ene_25

array([4.45223223, 3.51383354, 3.91191359, 4.78031232, 4.52344706,
       2.56611897, 3.89220187, 3.13437591, 3.16749647, 3.52101744,
       3.33762006, 4.23909557, 3.76212961, 3.32222986, 3.54390453,
       3.46809142, 4.26648293, 3.09735925, 3.45391348, 2.65087179,
       1.48198429, 3.68822219, 3.8332707 , 2.72788331, 4.8001698 ,
       2.23786898, 3.26999714, 3.10972616, 4.29310973, 4.24947466,
       3.34512222, 3.49870056, 2.62769211, 1.8756696 , 2.99914052,
       3.34608652, 4.084989  , 4.06578556, 2.9720221 , 3.03052108,
       2.51707968, 2.2615012 ])

In [29]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(0)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[4], scale=sim_rem.StandDev.iloc[4], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[4] - sim_rem.Percentile_25.iloc[4]) + sim_rem.Percentile_25.iloc[4]

# Adjust median
median_adjustment = sim_rem.Median.iloc[4] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
dec_24 = df['Final'].to_numpy()
dec_24

array([5.00297631, 3.75177805, 4.28255145, 5.44041642, 5.09792941,
       2.48815863, 4.25626916, 3.24583455, 3.2899953 , 3.76135659,
       3.51682675, 4.71879409, 4.08283948, 3.49630648, 3.7918727 ,
       3.69078856, 4.75531057, 3.196479  , 3.67188463, 2.60116239,
       1.04264572, 3.98429625, 4.17769427, 2.70384442, 5.46689306,
       2.05049198, 3.42666286, 3.21296822, 4.79081297, 4.73263288,
       3.52682963, 3.73160075, 2.57025614, 1.56755947, 3.06552069,
       3.52811537, 4.51331867, 4.48771408, 3.0293628 , 3.10736144,
       2.42277291, 2.0820016 ])

In [28]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(0)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[3], scale=sim_rem.StandDev.iloc[3], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[3] - sim_rem.Percentile_25.iloc[3]) + sim_rem.Percentile_25.iloc[3]

# Adjust median
median_adjustment = sim_rem.Median.iloc[3] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
nov_24 = df['Final'].to_numpy()
nov_24

array([4.46914692, 3.42648171, 3.86879287, 4.83368035, 4.54827451,
       2.37346552, 3.84689096, 3.00486212, 3.04166275, 3.43446383,
       3.23068896, 4.23232841, 3.70236623, 3.21358873, 3.45989392,
       3.37565713, 4.26275881, 2.9637325 , 3.35990386, 2.46763532,
       1.16887143, 3.62024688, 3.78141189, 2.55320368, 4.85574422,
       2.00874331, 3.15555238, 2.97747351, 4.29234414, 4.24386073,
       3.23902469, 3.40966729, 2.44188012, 1.60629956, 2.85460057,
       3.24009614, 4.06109889, 4.03976173, 2.824469  , 2.88946787,
       2.31897742, 2.03500134])

In [27]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(0)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[2], scale=sim_rem.StandDev.iloc[2], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[2] - sim_rem.Percentile_25.iloc[2]) + sim_rem.Percentile_25.iloc[2]

# Adjust median
median_adjustment = sim_rem.Median.iloc[2] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
oct_24 = df['Final'].to_numpy()
oct_24


array([4.55223223, 3.61383354, 4.01191359, 4.88031232, 4.62344706,
       2.66611897, 3.99220187, 3.23437591, 3.26749647, 3.62101744,
       3.43762006, 4.33909557, 3.86212961, 3.42222986, 3.64390453,
       3.56809142, 4.36648293, 3.19735925, 3.55391348, 2.75087179,
       1.58198429, 3.78822219, 3.9332707 , 2.82788331, 4.9001698 ,
       2.33786898, 3.36999714, 3.20972616, 4.39310973, 4.34947466,
       3.44512222, 3.59870056, 2.72769211, 1.9756696 , 3.09914052,
       3.44608652, 4.184989  , 4.16578556, 3.0720221 , 3.13052108,
       2.61707968, 2.3615012 ])

In [40]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(1)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[1], scale=sim_rem.StandDev.iloc[1], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[1] - sim_rem.Percentile_25.iloc[1]) + sim_rem.Percentile_25.iloc[1]

# Adjust median
median_adjustment = sim_rem.Median.iloc[1] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
sep_24 = df['Final'].to_numpy()
sep_24


array([4.36011953, 3.33869586, 3.3768763 , 3.12801983, 4.01344615,
       2.56682419, 4.41514709, 3.27042873, 3.76387175, 3.50422933,
       4.28601148, 2.67709181, 3.47086244, 3.44270735, 4.13603051,
       3.11572189, 3.53937556, 3.21714376, 3.63742135, 3.88436142,
       3.11538939, 4.14103428, 4.02997414, 3.84767184, 4.0296385 ,
       3.3058202 , 3.5620039 , 3.19069072, 3.49577067, 3.86039846,
       3.30219655, 3.43690653, 3.30424664, 3.23205914, 3.3115217 ,
       3.6123536 , 3.10776507, 3.72521683, 4.37631576, 3.95709524,
       3.53051053, 3.21268069])

In [24]:
n_obs = 42  # Number of observations

# Create an initial sample
np.random.seed(0)  # For reproducibility
observations = np.random.normal(loc=sim_rem.Median.iloc[0], scale=sim_rem.StandDev.iloc[0], size=n_obs)

# Convert to a DataFrame for better handling
df = pd.DataFrame(observations, columns=["Value"])

# Adjust to approximate quartiles
# Using quantile function to get the current Q1 and Q3 from the sample
current_Q1 = df['Value'].quantile(0.25)
current_Q3 = df['Value'].quantile(0.75)

# Scale the data to fit the desired Q1, median, Q3
df['Scaled'] = ((df['Value'] - current_Q1) / (current_Q3 - current_Q1)) * (sim_rem.Percentile_75.iloc[0] - sim_rem.Percentile_25.iloc[0]) + sim_rem.Percentile_25.iloc[0]

# Adjust median
median_adjustment = sim_rem.Median.iloc[0] - df['Scaled'].median()
df['Final'] = df['Scaled'] + median_adjustment

# Take the final values
august_24 = df['Final'].to_numpy()
august_24

array([4.13382938, 3.92529634, 4.01375857, 4.20673607, 4.1496549 ,
       3.7146931 , 4.00937819, 3.84097242, 3.84833255, 3.92689277,
       3.88613779, 4.08646568, 3.98047325, 3.88271775, 3.93197878,
       3.91513143, 4.09255176, 3.8327465 , 3.91198077, 3.73352706,
       3.47377429, 3.96404938, 3.99628238, 3.75064074, 4.21114884,
       3.64174866, 3.87111048, 3.8354947 , 4.09846883, 4.08877215,
       3.88780494, 3.92193346, 3.72837602, 3.56125991, 3.81092011,
       3.88801923, 4.05221978, 4.04795235, 3.8048938 , 3.81789357,
       3.70379548, 3.64700027])

In [41]:

sim_rem_df = pd.DataFrame({"Aug 24":august_24, "Sep 24":sep_24, "Oct 24":oct_24, "Nov 24":nov_24, "Dec 24":dec_24, "Jan 25":ene_25, "Feb 25":feb_25})


In [42]:
sim_rem_df

Aug 24    Sep 24    Oct 24    Nov 24    Dec 24    Jan 25    Feb 25
0   4.133829  4.360120  4.552232  4.469147  5.002976  4.452232  4.686062
1   3.925296  3.338696  3.613834  3.426482  3.751778  3.513834  3.539130
2   4.013759  3.376876  4.011914  3.868793  4.282551  3.911914  4.025672
3   4.206736  3.128020  4.880312  4.833680  5.440416  4.780312  5.087048
4   4.149655  4.013446  4.623447  4.548275  5.097929  4.523447  4.773102
5   3.714693  2.566824  2.666119  2.373466  2.488159  2.566119  2.380812
6   4.009378  4.415147  3.992202  3.846891  4.256269  3.892202  4.001580
7   3.840972  3.270429  3.234376  3.004862  3.245835  3.134376  3.075348
8   3.848333  3.763872  3.267496  3.041663  3.289995  3.167496  3.115829
9   3.926893  3.504229  3.621017  3.434464  3.761357  3.521017  3.547910
10  3.886138  4.286011  3.437620  3.230689  3.516827  3.337620  3.323758
11  4.086466  2.677092  4.339096  4.232328  4.718794  4.239096  4.425561
12  3.980473  3.470862  3.862130  3.702366  4.082839  3.762130  3.842603
13  3.882718  3.442707  3.422230  3.213589  3.496306  3.322230  3.304948
14  3.931979  4.136031  3.643905  3.459894  3.791873  3.543905  3.575883
15  3.915131  3.115722  3.568091  3.375657  3.690789  3.468091  3.483223
16  4.092552  3.539376  4.366483  4.262759  4.755311  4.266483  4.459035
17  3.832747  3.217144  3.197359  2.963733  3.196479  3.097359  3.030106
18  3.911981  3.637421  3.553913  3.359904  3.671885  3.453913  3.465894
19  3.733527  3.884361  2.750872  2.467635  2.601162  2.650872  2.484399
20  3.473774  3.115389  1.581984  1.168871  1.042646  1.481984  1.055759
21  3.964049  4.141034  3.788222  3.620247  3.984296  3.688222  3.752272
22  3.996282  4.029974  3.933271  3.781412  4.177694  3.833271  3.929553
23  3.750641  3.847672  2.827883  2.553204  2.703844  2.727883  2.578524
24  4.211149  4.029639  4.900170  4.855744  5.466893  4.800170  5.111319
25  3.641749  3.305820  2.337869  2.008743  2.050492  2.237869  1.979618
26  3.871110  3.562004  3.369997  3.155552  3.426663  3.269997  3.241108
27  3.835495  3.190691  3.209726  2.977474  3.212968  3.109726  3.045221
28  4.098469  3.495771  4.393110  4.292344  4.790813  4.293110  4.491579
29  4.088772  3.860398  4.349475  4.243861  4.732633  4.249475  4.438247
30  3.887805  3.302197  3.445122  3.239025  3.526830  3.345122  3.332927
31  3.921933  3.436907  3.598701  3.409667  3.731601  3.498701  3.520634
32  3.728376  3.304247  2.727692  2.441880  2.570256  2.627692  2.456068
33  3.561260  3.232059  1.975670  1.606300  1.567559  1.875670  1.536930
34  3.810920  3.311522  3.099141  2.854601  3.065521  2.999141  2.910061
35  3.888019  3.612354  3.446087  3.240096  3.528115  3.346087  3.334106
36  4.052220  3.107765  4.184989  4.061099  4.513319  4.084989  4.237209
37  4.047952  3.725217  4.165786  4.039762  4.487714  4.065786  4.213738
38  3.804894  4.376316  3.072022  2.824469  3.029363  2.972022  2.876916
39  3.817894  3.957095  3.130521  2.889468  3.107361  3.030521  2.948415
40  3.703795  3.530511  2.617080  2.318977  2.422773  2.517080  2.320875
41  3.647000  3.212681  2.361501  2.035001  2.082002  2.261501  2.008501

In [43]:
sim_rem_df.describe()

Aug 24     Sep 24     Oct 24     Nov 24     Dec 24     Jan 25  \
count  42.000000  42.000000  42.000000  42.000000  42.000000  42.000000   
mean    3.900638   3.567420   3.502873   3.303192   3.603831   3.402873   
std     0.168741   0.438867   0.759335   0.843705   1.012446   0.759335   
min     3.473774   2.566824   1.581984   1.168871   1.042646   1.481984   
25%     3.812663   3.278371   3.106986   2.863317   3.075981   3.006986   
50%     3.900000   3.500000   3.500000   3.300000   3.600000   3.400000   
75%     4.012663   3.878371   4.006986   3.863317   4.275981   3.906986   
max     4.211149   4.415147   4.900170   4.855744   5.466893   4.800170   

          Feb 25  
count  42.000000  
mean    3.403511  
std     0.928076  
min     1.055759  
25%     2.919649  
50%     3.400000  
75%     4.019649  
max     5.111319

In [44]:
file_path = '/content/drive/MyDrive/Investigacion/paper AI/sim_rem.xlsx'

sim_rem_df.to_excel(file_path, index=False)
